title: Qingqin Fang's Personal Website
author: Qingqin Fang

navbar-links:
  Home: "/"
  About: "/about/"
  Projects: "/projects/"
  Blog: "/blog/"
  Contact: "/contact/"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "qingqin.fang@anu.edu.au"
  linkedin: qingqin-fang-a01572266
  github: your-github-username

rss-description: Personal blog and portfolio of Qingqin Fang

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "qingqinfang.com"

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false
keywords: "Qingqin Fang, Computing, AI, Software Development, Data Analysis, Machine Learning"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

timezone: "Australia/Sydney"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
